/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef iot_protocol_CONSTANTS_H
#define iot_protocol_CONSTANTS_H

#include "iot_protocol_types.h"



class iot_protocolConstants {
 public:
  iot_protocolConstants();

};

extern const iot_protocolConstants g_iot_protocol_constants;



#endif
