/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "iot_protocol_constants.h"



const iot_protocolConstants g_iot_protocol_constants;

iot_protocolConstants::iot_protocolConstants() {
}



